In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestRegressor 
from sklearn.metrics import mean_squared_error

In [2]:
train = pd.read_csv("../input/30-days-of-ml/train.csv",index_col=0)
test = pd.read_csv("../input/30-days-of-ml/test.csv",index_col=0)
train.head()

,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,...,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,target
id,,,,,,,,,,,,,,,,,,,,,
1,B,B,B,C,B,B,A,E,C,N,...,0.400361,0.160266,0.310921,0.389470,0.267559,0.237281,0.377873,0.322401,0.869850,8.113634
2,B,B,A,A,B,D,A,F,A,O,...,0.533087,0.558922,0.516294,0.594928,0.341439,0.906013,0.921701,0.261975,0.465083,8.481233
3,A,A,A,C,B,D,A,D,A,F,...,0.650609,0.375348,0.902567,0.555205,0.843531,0.748809,0.620126,0.541474,0.763846,8.364351
4,B,B,A,C,B,D,A,E,C,K,...,0.668980,0.239061,0.732948,0.679618,0.574844,0.346010,0.714610,0.540150,0.280682,8.049253
6,A,A,A,C,B,D,A,E,A,N,...,0.686964,0.420667,0.648182,0.684501,0.956692,1.000773,0.776742,0.625849,0.250823,7.972260

In [3]:
y=train['target']
featuers=train.drop(['target'],axis=1)
featuers.head()

,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,...,cont4,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13
id,,,,,,,,,,,,,,,,,,,,,
1,B,B,B,C,B,B,A,E,C,N,...,0.610706,0.400361,0.160266,0.310921,0.389470,0.267559,0.237281,0.377873,0.322401,0.869850
2,B,B,A,A,B,D,A,F,A,O,...,0.276853,0.533087,0.558922,0.516294,0.594928,0.341439,0.906013,0.921701,0.261975,0.465083
3,A,A,A,C,B,D,A,D,A,F,...,0.285074,0.650609,0.375348,0.902567,0.555205,0.843531,0.748809,0.620126,0.541474,0.763846
4,B,B,A,C,B,D,A,E,C,K,...,0.284667,0.668980,0.239061,0.732948,0.679618,0.574844,0.346010,0.714610,0.540150,0.280682
6,A,A,A,C,B,D,A,E,A,N,...,0.287595,0.686964,0.420667,0.648182,0.684501,0.956692,1.000773,0.776742,0.625849,0.250823

In [4]:
from sklearn.preprocessing import OrdinalEncoder
s=(train.dtypes=='object')
object_cols=list(s[s].index)
x=featuers.copy()
x_test=test.copy()
ordinal_encoder=OrdinalEncoder()
x[object_cols]=ordinal_encoder.fit_transform(featuers[object_cols])
x_test[object_cols]=ordinal_encoder.fit_transform(test[object_cols])

In [5]:
x_train,x_valid,y_train,y_valid=train_test_split(x,y,random_state=0)

In [6]:
model=RandomForestRegressor(random_state=1)
model.fit(x_train,y_train)
pred_valid=model.predict(x_valid)
print(mean_squared_error(y_valid,pred_valid,squared=False))

0.7375392165180452

In [7]:
predictions=model.predict(x_test)
output=pd.DataFrame({'Id':x_test.index,'target':predictions})
output.to_csv('submissions.csv',index=False)